from __future__ import annotations
from pydantic import BaseModel
from typing import Optional
from app.schemas.profile import UserProfile
from app.schemas.simulation import SimulationResult
from app.schemas.risk import RiskReport


class StrategyAction(BaseModel):
    id: str
    title: str
    description: str
    category: str  # "savings" | "allocation" | "tax" | "insurance" | "income" | "spending"
    projected_impact: str
    priority: int  # 1 = highest
    approved: Optional[bool] = None


class AdvisorResponse(BaseModel):
    strategy_actions: list[StrategyAction]
    narrative: str
    disclaimer: str = (
        "This analysis is generated by an AI and is for informational purposes only. "
        "It does not constitute financial advice. Consult a licensed financial advisor "
        "before making investment decisions."
    )


class RecommendRequest(BaseModel):
    profile: UserProfile
    simulation_result: SimulationResult
    risk_report: RiskReport


class ChatMessage(BaseModel):
    role: str  # "user" | "assistant"
    content: str


class ChatRequest(BaseModel):
    profile: UserProfile
    simulation_result: SimulationResult
    risk_report: RiskReport
    messages: list[ChatMessage]
