from __future__ import annotations
"""
Parses and validates Claude's JSON strategy response into AdvisorResponse.
Handles malformed JSON gracefully with a fallback response.
"""
import json
import re
from app.schemas.advisor import AdvisorResponse, StrategyAction

DISCLAIMER = (
    "This analysis is generated by an AI and is for informational purposes only. "
    "It does not constitute financial advice. Consult a licensed financial advisor "
    "before making investment decisions."
)

FALLBACK_RESPONSE = AdvisorResponse(
    strategy_actions=[
        StrategyAction(
            id="fallback_1",
            title="Review your financial plan with an advisor",
            description=(
                "Our AI advisor encountered an issue generating personalized recommendations. "
                "Please consult a licensed financial advisor for a detailed review of your plan."
            ),
            category="savings",
            projected_impact="Varies based on specific guidance",
            priority=1,
        )
    ],
    narrative=(
        "We were unable to generate detailed recommendations at this time. "
        "Your simulation results are still available for review."
    ),
    disclaimer=DISCLAIMER,
)


def parse_strategy_response(raw_text: str) -> AdvisorResponse:
    """Parse Claude's raw text into AdvisorResponse. Falls back gracefully."""
    # Strip markdown code fences if present
    text = raw_text.strip()
    text = re.sub(r"^```(?:json)?\s*", "", text)
    text = re.sub(r"\s*```$", "", text)

    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        # Try to extract JSON object from text
        match = re.search(r"\{.*\}", text, re.DOTALL)
        if not match:
            return FALLBACK_RESPONSE
        try:
            data = json.loads(match.group())
        except json.JSONDecodeError:
            return FALLBACK_RESPONSE

    try:
        actions_raw = data.get("strategy_actions", [])
        actions = []
        for i, a in enumerate(actions_raw):
            actions.append(
                StrategyAction(
                    id=a.get("id", f"action_{i+1}"),
                    title=a.get("title", "Strategy Recommendation"),
                    description=a.get("description", ""),
                    category=a.get("category", "savings"),
                    projected_impact=a.get("projected_impact", ""),
                    priority=int(a.get("priority", i + 1)),
                )
            )
        # Sort by priority
        actions.sort(key=lambda x: x.priority)

        return AdvisorResponse(
            strategy_actions=actions,
            narrative=data.get("narrative", ""),
            disclaimer=DISCLAIMER,
        )
    except Exception:
        return FALLBACK_RESPONSE
